# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.locale_extension:
        public:    false
        class:     AppBundle\Twig\LocaleExtension
        arguments: ["%app_locales%"]
        tags:
            - { name: twig.extension }

    app.comunidad.provider:
       class: AppBundle\Services\ComunidadProvider
       arguments: [@session, @doctrine.orm.default_entity_manager]

    app.jugadores.factory:
        class: AppBundle\Factory\JugadoresFactory
        autowire: true

    app.equipo.factory:
        class: AppBundle\Factory\EquipoFactory
        autowire: true

    app.partido.factory:
        class: AppBundle\Factory\PartidoFactory
        autowire: true

    app.comunidad.listener:
        class: AppBundle\Listener\ComunidadListener
        arguments: [@security.token_storage, @app.comunidad.provider, @controller_resolver, @logger]
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.controller', method: 'onKernelController' }

    app.form.jugador:
        class: AppBundle\Form\JugadorType
        autowire: true
        tags:
            - { name: form.type }




